### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by lly835** [skynetcapital/solanaj#83]
1.6-SNAPSHOT

java.lang.NoSuchMethodError: okhttp3.RequestBody.create(Ljava/lang/String;Lokhttp3/MediaType;)Lokhttp3/RequestBody;

	at org.p2p.solanaj.rpc.RpcClient.call(RpcClient.java:56)
	at org.p2p.solanaj.rpc.RpcApi.getBalance(RpcApi.java:98)
	at org.p2p.solanaj.rpc.RpcApi.getBalance(RpcApi.java:87)

**Comment by skynetcapital** [comment]
Did you type `mvn clean install` in the `solanaj` directory, _and_ in your `solana-batch` directory? You need to do it in both places.

**Comment by lly835** [comment]
mvn dependency:tree in your solana-batch directory

```
[INFO] 
[INFO] ----------------------< com.example:solana-batch >----------------------
[INFO] Building solana-batch 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.2:tree (default-cli) @ solana-batch ---
[INFO] com.example:solana-batch:jar:0.0.1-SNAPSHOT
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.5.0:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.5.0:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:2.5.0:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.5.0:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.5.0:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.14.1:compile
[INFO] |  |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.14.1:compile
[INFO] |  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.30:compile
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.28:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.5.0:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.12.3:compile
[INFO] |  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.12.3:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.12.3:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.12.3:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.12.3:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.12.3:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.5.0:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.46:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.46:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.46:compile
[INFO] |  +- org.springframework:spring-web:jar:5.3.7:compile
[INFO] |  |  \- org.springframework:spring-beans:jar:5.3.7:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.3.7:compile
[INFO] |     +- org.springframework:spring-aop:jar:5.3.7:compile
[INFO] |     +- org.springframework:spring-context:jar:5.3.7:compile
[INFO] |     \- org.springframework:spring-expression:jar:5.3.7:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.5.0:test
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:2.5.0:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.5.0:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.5.0:test
[INFO] |  |  +- net.minidev:json-smart:jar:2.4.7:test
[INFO] |  |  |  \- net.minidev:accessors-smart:jar:2.4.7:test
[INFO] |  |  |     \- org.ow2.asm:asm:jar:9.1:test
[INFO] |  |  \- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:test
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:test
[INFO] |  +- org.assertj:assertj-core:jar:3.19.0:test
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.7.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.7.2:test
[INFO] |  |  |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
[INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  |  |  \- org.junit.platform:junit-platform-commons:jar:1.7.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.7.2:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.7.2:test
[INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.7.2:test
[INFO] |  +- org.mockito:mockito-core:jar:3.9.0:test
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.10.22:test
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.10.22:test
[INFO] |  |  \- org.objenesis:objenesis:jar:3.2:test
[INFO] |  +- org.mockito:mockito-junit-jupiter:jar:3.9.0:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.0:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  +- org.springframework:spring-core:jar:5.3.7:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.3.7:compile
[INFO] |  +- org.springframework:spring-test:jar:5.3.7:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.8.2:test
[INFO] \- org.p2p:solanaj:jar:1.6-SNAPSHOT:compile
[INFO]    +- org.bitcoinj:bitcoinj-core:jar:0.15.10:compile
[INFO]    |  +- org.bouncycastle:bcprov-jdk15to18:jar:1.68:compile
[INFO]    |  +- com.google.protobuf:protobuf-java:jar:3.6.1:compile
[INFO]    |  +- com.google.guava:guava:jar:28.2-android:runtime
[INFO]    |  |  +- com.google.guava:failureaccess:jar:1.0.1:runtime
[INFO]    |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:runtime
[INFO]    |  |  +- com.google.code.findbugs:jsr305:jar:3.0.2:runtime
[INFO]    |  |  +- org.checkerframework:checker-compat-qual:jar:2.5.5:runtime
[INFO]    |  |  +- com.google.errorprone:error_prone_annotations:jar:2.3.4:runtime
[INFO]    |  |  \- com.google.j2objc:j2objc-annotations:jar:1.3:runtime
[INFO]    |  \- net.jcip:jcip-annotations:jar:1.0:runtime
[INFO]    +- com.squareup.okhttp3:okhttp:jar:3.14.9:compile
[INFO]    |  \- com.squareup.okio:okio:jar:1.17.2:compile
[INFO]    +- com.squareup.moshi:moshi:jar:1.12.0:compile
[INFO]    |  \- org.jetbrains.kotlin:kotlin-stdlib:jar:1.5.0:compile
[INFO]    |     +- org.jetbrains:annotations:jar:13.0:compile
[INFO]    |     \- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.5.0:compile
[INFO]    +- com.squareup.moshi:moshi-adapters:jar:1.12.0:compile
[INFO]    +- org.java-websocket:Java-WebSocket:jar:1.5.2:compile
[INFO]    +- org.projectlombok:lombok:jar:1.18.20:compile
[INFO]    \- net.i2p.crypto:eddsa:jar:0.3.0:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.595 s
[INFO] Finished at: 2021-07-05T15:44:55+08:00
[INFO] ------------------------------------------------------------------------
(base) ➜  solana-batch git:(master) 

```

**Comment by grmkris** [comment]
https://github.com/skynetcapital/solanaj/pull/87

I made a temporary fix here
